### ISSUE TITLE
jsmol image broken

### ISSUE THREAD

**Issue by xiangjf** [openedx/openedx-demo-course#10]
The image files Al2O3.png and 1hxw.png under static/jsmol broken, leading to the failure when import course. 

2014-06-03 22:54:28,439 ERROR 5089 [root] content.py:233 - Failed to generate thumbnail for c4x://edX/Open_DemoX/asset/jsmol_Al2O3.png. Exception: cannot identify image file
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/contentstore/content.py", line 212, in generate_thumbnail
    im = Image.open(StringIO.StringIO(content.data))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/PIL/Image.py", line 1978, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file
2014-06-03 22:54:28,685 ERROR 5089 [root] content.py:233 - Failed to generate thumbnail for c4x://edX/Open_DemoX/asset/jsmol_1hxw.png. Exception: cannot identify image file
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/contentstore/content.py", line 212, in generate_thumbnail
    im = Image.open(StringIO.StringIO(content.data))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/PIL/Image.py", line 1978, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file

**Comment by chenshuchuan** [comment]
When I import course I also encountered such a problem

**Comment by jswope00** [comment]
This issue is 10 years old now :) 

The original demoX course has been replaced the jsmol problem is no longer a component in the course.
